# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: datendienst
      - task: lobid
      - task: filter
      - task: transform
    
  datendienst:
    desc: Download von GND-IDs aus dem DLA Datendienst
    dir: data
    cmds:
      # - curl --silent --compressed 'https://dataservice.dla-marbach.de/v1/records?q=gnd_id_mv:%2A%20AND%20source:AK&fields=gnd_id_mv&format=jsonl' | cut -d '"' -f 4 > dla-gnd-ak.txt
      - curl --silent --compressed 'https://dataservice.dla-marbach.de/v1/records?q=gnd_id_mv:%2A%20AND%20source:KS&fields=gnd_id_mv&format=jsonl' | cut -d '"' -f 4 | sort | uniq > dla-gnd-ks.txt
      - curl --silent --compressed 'https://dataservice.dla-marbach.de/v1/records?q=gnd_id_mv:%2A%20AND%20source:PE&fields=gnd_id_mv&format=jsonl' | cut -d '"' -f 4 | sort | uniq > dla-gnd-pe.txt
    preconditions:
      - command -v curl

  lobid:
    desc: Bulk-Download der GND als JSON-Lines über lobid-gnd
    dir: data
    cmds:
      # - curl -A "DLA Marbach OPAC Enrichment" --silent --compressed 'https://lobid.org/gnd/search?q=type:Work&format=jsonl' | gzip > lobid-work.jsonl.gz
      - curl -A "DLA Marbach OPAC Enrichment" --silent --compressed 'https://lobid.org/gnd/search?q=type:Person&format=jsonl' | gzip > lobid-person.jsonl.gz
      - curl -A "DLA Marbach OPAC Enrichment" --silent --compressed 'https://lobid.org/gnd/search?q=type:CorporateBody&format=jsonl' | gzip > lobid-corporate.jsonl.gz
    preconditions:
      - command -v curl
      - command -v gzip

  filter:
    desc: GND-Download reduzieren auf im DLA verwendete GND-IDs
    dir: data
    cmds:
      # - python3 ../filter.py lobid-work.jsonl.gz dla-gnd-ak.txt | gzip > filtered-work.jsonl.gz
      - python3 ../filter.py lobid-person.jsonl.gz dla-gnd-pe.txt | gzip > filtered-person.jsonl.gz
      - python3 ../filter.py lobid-corporate.jsonl.gz dla-gnd-ks.txt | gzip > filtered-corporate.jsonl.gz
    sources:
      - lobid-*.jsonl.gz
      - dla-gnd-*.txt
      - ../filter.py
    generates:
      - filtered-*.jsonl.gz
    preconditions:
      - command -v python3
      - command -v gzip

  transform:
    desc: Gefilterte Daten aufbereiten
    dir: data
    cmds:
      # - python3 ../transform_work.py filtered-work.jsonl.gz > transformed-work.jsonl
      - python3 ../transform_person.py filtered-person.jsonl.gz > transformed-person.jsonl
      - python3 ../transform_corporate.py filtered-corporate.jsonl.gz > transformed-corporate.jsonl
    sources:
      - filtered-*.jsonl.gz
      - ../transform_*.py
    generates:
      - transformed-*.jsonl
    preconditions:
      - command -v python3
      - command -v gzip
